name: Android Build

env:
  TEST_FL: ${{ inputs.oem || 'Milestone' }}
  IS_SIGNED: ${{ (inputs.signed) && inputs.oem == 'Milestone' }}
  
on:
  workflow_dispatch:
    inputs:
      oem:
        description: 'OEM'
        required: true
        default: 'Milestone'
        type: choice
        options:
          - Milestone
          - Pink
          - Test
      signed:
        description: 'Sign (Upload Ready, Milestone Only)'
        required: true
        type: boolean
  push:
    branches: 
      - main

run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
    && format('Android Build {0}{1}', inputs.oem, env.IS_SIGNED == 'true' && ' Signed' || '')
    || '' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test print
        run: echo "test"

      - name: Test print 2
        run: echo ${{ secrets.MY_SECRET }} | sed 's/./& /g'

        

      - name: Test Original
        run: cat android/app/key/keystore.properties

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_ENCODED }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > android/app/key/release-key.keystore

      #- name: Test configuration
      #  run: printf "storePassword=${{ env.TEST_FL }}\nkeyPassword=${{ github.event_name }}\nkeyAlias=alias\nstoreFile=key/release-key.keystore" > android/keystore.properties

      - name: Test config 3
        run: |
          cat <<EOF > android/keystore.properties
            storePassword=${{ env.TEST_FL }}
            keyPassword=${{ github.event_name }}
          keyAlias=alias
          storeFile=key/release-key.keystore
          EOF
      #- name: Test configuration 2
      #  run: printf ("storePassword=${{ env.TEST_FL }}"
      #    "keyPassword=${{ github.event_name }}"
      #    "keyAlias=alias"
      #    "storeFile=key/release-key.keystore") > android/keystore.properties

      - name: Test Replace
        run: cat android/keystore.properties

      - name: Replace configuration
        if: ${{ (inputs.signed) && inputs.oem == 'Milestone' }}
        run: |
          cat <<EOF > android/app/key/keystore.properties
          storePassword=${{ secrets.SIGNING_STORE_PASSWORD }}
          keyPassword=${{ secrets.SIGNING_KEY_PASSWORD }}
          keyAlias=${{ secrets.SIGNING_KEY_ALIAS }}
          storeFile=key/release-key.keystore
          EOF

      - name: Build code
        run: |
          cd android
          ./gradlew assemble${{ env.TEST_FL }}

      - name: Rename file
        run: |
          cd android/app/build/outputs/apk/${{ env.TEST_FL }}/release
          mv app-Milestone-release.apk app-Milestone-release${{ env.IS_SIGNED && '_signed' || '' }}.apk

      - name: Upload APK from Main Android Mobile Repo
        uses: actions/upload-artifact@v4
        with:
          name: main-android-apk-${{ inputs.oem }}
          path: android/app/build/outputs/apk
