name: Android Build

on:
  workflow_dispatch:
    inputs:
      oem:
        description: 'OEM'
        required: true
        default: 'Milestone'
        type: choice
        options:
          - Milestone
          - Pink
          - Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'adopt'

      - name: Test1
        run: pwd

      - name: Change dir
        run: cd android

      - name: Test2
        run: pwd

      - name: Test print
        run: ls -la

      - name: Test permission
        run: chmod +x gradlew

      - name: Build code
        run: bash ./gradlew assembleMilestone

      - name: Upload APK from Main Android Mobile Repo
        uses: actions/upload-artifact@v4
        with:
          name: main-android-apk
          path: build/outputs/apk
