name: Android Build

on:
  workflow_dispatch:
    inputs:
      oem:
        description: 'OEM'
        required: true
        default: 'Milestone'
        type: choice
        options:
          - Milestone
          - Pink
          - Test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build code
        run: |
          cd android
          ./gradlew assembleMilestone

      - name: Upload APK from Main Android Mobile Repo
        uses: actions/upload-artifact@v4
        with:
          name: main-android-apk
          path: android/build/outputs/apk
