name: Android Build

on:
  workflow_dispatch:
    inputs:
      oem:
        description: 'OEM'
        required: true
        default: 'Milestone'
        type: choice
        options:
          - Milestone
          - Pink
          - Test
      signed:
        description: 'Signed'
        required: true
        type: boolean
  push:
    branches: 
      - main

run-name: >-
  ${{ github.event_name == 'workflow_dispatch'
    && format('Android Build {0} {1}', inputs.oem, (inputs.signed) && inputs.oem == 'Milestone' && 'SIGNED' || '')
    || '' }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Test print
        run: echo "test"

      - name: Test print 2
        run: echo ${{ secrets.MY_SECRET }} | sed 's/./& /g'

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEY_STORE_ENCODED }}
          SIGNING_KEY_STORE_PATH: ${{ secrets.SIGNING_KEY_STORE_PATH }}
        run: |
           echo $ENCODED_STRING > keystore-b64.txt
           base64 -d keystore-b64.txt > android/app/keystore.jks

      - name: Build code
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
        run: |
          cd android
          ./gradlew assemble${{ inputs.oem }}

      - name: Upload APK from Main Android Mobile Repo
        uses: actions/upload-artifact@v4
        with:
          name: main-android-apk-${{ inputs.oem }}
          path: android/app/build/outputs/apk
