name: Test PR Build

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Make Changes
        env:
          BRANCH_NAME: test_branch_${{ github.run_number }}
        run: |
          git config --global user.name "User-Test1"
          git config --global user.email "tpt@milestone.dk"  
          
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          echo "test$(git rev-parse HEAD)" >> test1.txt
          git add test1.txt
          echo "test$(git rev-parse HEAD)" >> test2.txt
          git add test2.txt

      - name: Prepare variable
        run: |
          echo "COMMAND_VALUE_1=git add ." >> $GITHUB_ENV
          echo "COMMAND_VALUE_2=git diff --staged --name-only > changed_files.txt" >> $GITHUB_ENV
          echo "COMMAND_VALUE_3=echo \"Changed files:\"\ncat changed_files.txt" >> $GITHUB_ENV
  


          
      - name: Commit Changes
        env:
          BRANCH_NAME: test_branch_${{ github.run_number }}
        run: |
          eval $COMMAND_VALUE_1

          eval $COMMAND_VALUE_2

          eval $COMMAND_VALUE_3

          echo "5"
          ${{ env.COMMAND_VALUE_3 }}

          additions=()
          files=($(cat changed_files.txt))

          echo "Files array:"
          for file in "${files[@]}"; do
            echo "$file"
          done

          for file in "${files[@]}"; do
            content=$(cat "$file" | base64)
            echo "File: $file, Content: $content"
            additions+=("{\"path\": \"$file\", \"contents\": \"$content\"}")
          done

          additions_json=$(printf '%s\n' "${additions[@]}" | jq -s .)
          echo "Additions JSON:"
          echo "$additions_json"

          gh api graphql \
            -F githubRepository="tpt-milestone/intro-github" \
            -F branchName=$BRANCH_NAME \
            -F expectedHeadOid=$(git rev-parse HEAD) \
            -F commitMessage="Updated some files" \
            -F files="$additions_json" \
            -F 'query=@.github/api/createCommitOnBranch.gql'
