name: Test PR Build

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Make Changes
        env:
          BRANCH_NAME: test_branch_${{ github.run_number }}
        run: |
          git config --global user.name "User-Test1"
          git config --global user.email "tpt@milestone.dk"  
          
          git checkout -b $BRANCH_NAME
          git push -u origin $BRANCH_NAME
          echo "test$(git rev-parse HEAD)" >> test1.txt
          git add test1.txt
          echo "test$(git rev-parse HEAD)" >> test2.txt
          git add test2.txt

          
      - name: Commit Changes
        env:
          BRANCH_NAME: test_branch_${{ github.run_number }}
        run: |
          git add .
          
          git diff --staged --name-only > changed_files.txt
          
          additions=()
          files=($(cat changed_files.txt))

          echo "1"
          echo $files
          
          for file in "${files[@]}"; do
            echo "2"
            content=$(cat "$file" | base64)
            additions+=("{\"path\": \"$file\", \"contents\": \"$content\"}")
          done

          echo "3"
          echo $additions
          
          additions_json=$(printf '%s\n' "${additions[@]}" | jq -s .)
          echo "4"
          echo $additions_json
          
          echo "5"
          echo $(echo $additions_json | jq '.[0]')
          
          echo "6"
          echo $(echo $additions_json | jq '.[1]')

          echo "7"
          echo "${additions[0]}"
          
          echo "8"
          echo "${additions[1]}"

          p=()
          # Add JSON objects to the array
          p+=('{"path": "test1.txt", "contents": "dGVzdDEuLi4="}')
          p+=('{"path": "test2.txt", "contents": "dGVzdDIuLi4="}')

          # Convert the array to a JSON array
          p_json=$(printf '%s\n' "${p[@]}" | jq -s .)

          # Print the JSON array
          echo "$p_json"
          
          # Print the JSON array's first item
          echo $(echo $p_json | jq '.[0]')

          p5=()
          $p5[]={ path:"t1.txt", contents:"c1" }
          echo "10"
          echo "${p5[0]}"
          
          p6=()
          $p6[]={ "path":"t1.txt", "contents":"c1" }
          echo "10"
          echo "${p6[0]}"
        
          gh api graphql \
            -F githubRepository="tpt-milestone/intro-github" \
            -F branchName=$BRANCH_NAME \
            -F expectedHeadOid=$(git rev-parse HEAD) \
            -F commitMessage="Updated some files" \
            -F files=$p_json \
            -F 'query=@.github/api/createCommitOnBranch.gql'
