name: Test PR Build

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Create PR
        run: |
          git checkout -b test_branch origin/main
          touch test1.txt
          git add test1.txt
          git commit -m "Added test1.txt"
          git push origin test_branch
          PR_URL=$(gh pr create \
                --base main \
                --head test_branch \
                --title "Automated: Resources update" \
                --body "This PR tests." \
                --json url -q .url)
          echo "pr_created=true" >> $GITHUB_OUTPUT
          echo "pr_url=$PR_URL" >> $GITHUB_OUTPUT
