name: Test PR Build

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Create PR
        run: |
          git checkout -b test_branch
          git config --global user.name "User-Test1"
          git config --global user.email "tpt@milestone.dk"  
          echo "test$(git rev-parse HEAD)" >> test1.txt
          echo "test$(git rev-parse HEAD)" >> test2.txt
          git add .
          echo "0"
          git status
          echo "1"
          git diff --staged
          echo "2
          additions=()
          echo "3"
          echo $additions
          files=($(git diff --staged --name-only))
          for file in "${files[@]}"; do
            echo "4"
            content=$(cat "$file" | base64)
            additions+=("{\"path\": \"$file\", \"contents\": \"$content\"}")
          done
          
          echo "5"
          echo $additions

          git commit -m "Added test1.txt"
          git push origin test_branch
          
          additions_json=$(IFS=,; echo "${additions[*]}")
          echo $additions_json
