name: Test PR Build

on:
  workflow_dispatch:
  push:
    branches: 
      - test

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
      pages: write
      pull-requests: write
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Create PR
        run: |
          git checkout -b test_branch
          git config --global user.name "User-Test1"
          git config --global user.email "tpt@milestone.dk"  
          echo "test$(git rev-parse HEAD)" >> test1.txt
          echo "test$(git rev-parse HEAD)" >> test2.txt
          echo "0"
          git status
          echo "1"
          git diff
          echo "2"
          git diff --name-only
          additions=()
          echo "3"
          echo $additions
          for file in "$(git diff --name-only)"; do
            echo "4"
            content=$(cat "$file" | base64)
            additions+=("{\"path\": \"$file\", \"contents\": \"$content\"}")
          done

          echo "5"
          echo $additions
          for file in $(git diff --name-only); do
            echo "6"
            content=$(cat "$file" | base64)
            additions+=("{\"path\": \"$file\", \"contents\": \"$content\"}")
          done

          git add test1.txt
          git add test2.txt
          git commit -m "Added test1.txt"
          
          additions_json=$(IFS=,; echo "${additions[*]}")
