name: Test consequtive

on:
  workflow_run:
    workflows: [Test PR Build]
    types: [completed]

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          echo "success"
